version: '3.8'

services:
  family-calendar:
    build: .
    ports:
      - "5000:5000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - FLASK_ENV=production
    volumes:
      - calendar_data:/app/instance
    restart: unless-stopped

volumes:
  calendar_data: